build.gradle
src/main/java/ledger/database/storage/SQL/H2/H2Database.java
src/main/java/ledger/database/storage/SQL/H2/IH2Database.java
src/main/java/ledger/database/storage/SQL/ISQLDatabaseAccount.java
src/main/java/ledger/database/storage/SQL/ISQLDatabaseNote.java
src/main/java/ledger/database/storage/SQL/ISQLDatabasePayee.java
src/main/java/ledger/database/storage/SQL/ISQLDatabaseTag.java
src/main/java/ledger/database/storage/SQL/ISQLDatabaseTransaction.java
src/main/java/ledger/database/storage/SQL/ISQLDatabaseType.java
src/main/java/ledger/database/storage/SQL/SQLite/ISQLiteDatabase.java
src/main/java/ledger/database/storage/SQL/SQLite/SQLiteDatabase.java
src/main/java/ledger/database/storage/table/AccountBalanceTable.java
src/main/java/ledger/database/storage/table/AccountTable.java
src/main/java/ledger/database/storage/table/NoteTable.java
src/main/java/ledger/database/storage/table/PayeeTable.java
src/main/java/ledger/database/storage/table/TagTable.java
src/main/java/ledger/database/storage/table/TagToPayeeTable.java
src/main/java/ledger/database/storage/table/TagToTransTable.java
src/main/java/ledger/database/storage/table/TransactionTable.java
src/main/java/ledger/database/storage/table/TypeTable.java
src/test/java/ledger/H2Test.java
src/test/java/ledger/database/storage/H2DatabaseTest.java
src/test/java/ledger/database/storage/SQLiteDatabaseTest.java
src/test/java/ledger/io/importer/ImporterTest.java
src/test/java/ledger/io/input/DuplicateDetectorTest.java
src/test/resources/README.md

So there's a lot going on here, but its not terribly complicated. I'll try to explain so it makes a bit more sense. Encryption while still using SQLite was going to be a pain, so we abandoned it and switched to using [h2](http://www.h2database.com/html/main.html). H2 offers encryption build in (easy) and uses a subset of SQL for its query languages (pain the ass, but manageable). It also appears to be roughly 100x as fast.
I kept the SQLite files around, since support for multiple databases had been discussed. There's now a package for SQL databases. I abstracted some of the logic away from h2 and SQLite into interfaces for SQL databases in general.
Our database tests were copied over for h2. Some changes had to be made, as h2 is a little more picky about referential integrity. 
I can't …

[LED-76] Switch to h2 and enable encryption

---

src/main/java/ledger/database/entity/Account.java
src/main/java/ledger/database/entity/Payee.java
src/main/java/ledger/database/storage/SQL/ISQLDatabasePayee.java
src/main/java/ledger/database/storage/SQL/ISQLDatabaseTag.java
src/test/java/ledger/database/storage/EntityTests.java
src/test/java/ledger/database/storage/H2DatabaseTest.java
src/test/java/ledger/database/storage/SQLiteDatabaseTest.java

Ignore the wrong branch name, it's a struggle tonight.
- Fixed the payee boxes in the transaction table to not contain duplicate payees. 
- Fixed DB backend to not insert multiple of the same payee/tag
- fixed our tests to not suck (or suck less)
- wrote tests for this feature

[LED-95] Fixing Payee Duplicates

---

src/main/java/ledger/user_interface/ui_controllers/TransactionTableView.java
src/main/java/ledger/user_interface/ui_models/TransactionModel.java
src/main/java/ledger/user_interface/utils/LocalDateTableCell.java

I've implemented the embedded date picker for transaction dates.
Currently, the date picker is always present in the table, and when clicked on it goes into editing view (the whole calendar shows up). I've been tinkering with ways to get the table cells to display as plain text dates, but haven't figured it out yet. I figured I'd make a PR for this since the functionality is present and our sprint is coming to an end soon. Pull this code down and test it, please!
¡Muchas gracias!

[LED-96] Implemented embedded date picker

---

src/main/java/ledger/user_interface/ui_controllers/GenericPopupController.java
src/main/java/ledger/user_interface/ui_controllers/IUIController.java
src/main/java/ledger/user_interface/ui_controllers/MainPageController.java
src/main/java/ledger/user_interface/ui_controllers/PasswordPromptController.java

Fixed three issues that i found
- Closing the FileChooser would cause a NPE. It didnt hurt anything, but we can run a little more efficiently by not throwing unnecessary exceptions
- An incorrect password verification would throw exceptions and put the user back into the app anyway. The user could use the app like normal (with exceptions being thrown on every action) but nothing would persist after logout
- The object name of the title text in GenericErrorPopup was previously changed in the fxml but not the controller. Caused some funky behavior.

[LED-112] Implemented better error handling on data export

---

src/main/java/ledger/user_interface/ui_controllers/ExpenditureChartsController.java
src/main/resources/fxml_files/ExpenditureCharts.fxml

Expenditures page now has two functional charts. The LineChart on the left hand side shows the change in overall balance (how much they spent/deposited) each month for the last six months. This is a general overview of everything and is therefore not restricted by account. The PieChart on the right hand side is more dynamic. It will show proportions of how much was spent in each category (determined by tags, basically). It can be filtered by account and/or by date range. This chart doesn't look at deposits, only expenditures. I figured this was best in the case that the end user would want to see what they are spending most of their money on.
If you have any questions, or if something doesn't make sense, shoot me a slack message!

[LED-130] Statistics UI

---

src/main/java/ledger/user_interface/ui_controllers/FileSelectorButton.java
src/main/java/ledger/user_interface/ui_controllers/ImportTransactionsPopupController.java

I added the ability to set file extension filters for our custom FileSelectorButton UI controller. I've only set up filters for the Import Transactions popup, but this new feature can be used anywhere we use our FileSelectorButton. I added filters for .csv, .qfx, and all files (all case insensitive), as per Sean's request.

[LED-119] Implemented file extension filters

---

build.gradle

We were double defining dependencies.

Removing extra dependencies

---

src/main/java/ledger/user_interface/ui_controllers/ExpenditureChartsController.java

Added the amount spent to each category label. I brought the legend back after saying we didn't need it at standup because I found that if the chart slices were too small, a label wouldn't be displayed. I finally figured out how to get the chart colors to match the legend and still not recolor on resubmission of data.

Statistics UI Improvements

---

src/main/java/ledger/user_interface/ui_controllers/TransactionTableView.java

I've been working on implementing this feature, but has run into a bug in my code. The only operation I'm concerned about with multiple selection is deleting transactions. Deleting a single selected transaction works, as does deleting multiple transactions which were selected by CTRL-clicking. The problem only occurs when SHIFT-clicking to select a range. When a SHIFT-click range is deleted, a null pointer exception will occasionally be throw when retrieving the Transaction from the TransactionModel. Unfortunately, I haven't been able to identify the cause, and it's quite difficult to replicate (it seems to occur randomly, ~10% of the time). I'd like to get some of you guys to test it and see if you can find something I might've missed. Thanks!

[LED-141] Multiple selection in the transaction table view

---

src/main/java/ledger/user_interface/ui_controllers/TransactionTableView.java

I added a right-click context menu with the ability to delete selected transactions to the table view. Pressing the delete key still works, but this might be functionality we'd consider removing. You can also use right-click in conjunction with CTRL-click and SHIFT-click to select and delete multiple transactions.

[LED-140] Implemented right-click context menu to delete transactions

---

src/main/java/ledger/user_interface/ui_controllers/window/ExpenditureChartsController.java

I found an error that had somehow made it into master. There was a label that was removed when the Expenditures UI was refactored a while ago, and for some reason the code still referenced it and would break when you clicked the enter button. I just removed it.

Fixed Expenditure Charts error on master

---

src/main/java/ledger/user_interface/ui_controllers/component/FilteringAccountDropdown.java
src/main/java/ledger/user_interface/ui_controllers/window/MainPageController.java

The account dropdown in the top left would not update correctly when an account was deleted by an action other then the Main Page's Delete account.
This bug was found in #162

Fix account dropdown

---

src/main/java/ledger/controller/DbController.java

Now when you log out the undo stack is cleared so if you log in again you can not use undo actions from previous db file.

Logout / Login Clear Undo Stack

---

src/main/java/ledger/updater/GitHubChecker.java

Changing the printing of the stack-trace to print out a descriptive error message.
Test by turning off your internet and running.

Stack-trace on Update Check with no Internet

---

src/main/java/ledger/user_interface/ui_controllers/IUIController.java
src/main/java/ledger/user_interface/ui_controllers/window/MainPageController.java

Addressing GitHub Issues #217 & #220
I changed the behavior of child modal so they block interaction with their parent (the main page) but are no longer forced to be on top. The error dialogues will now appear on top of the modal windows. The user will have to close (or complete & submit) the child modal to resume interaction with the main page window. This also prevents the user from logging out with child windows still open.
Unfortunately, this prohibits the user from using two application windows at once (though, I don't see many use cases for this besides maybe main page + expenditure charts). I can change it so the expenditure charts window does not block interaction with the main page, but then the expenditure charts window also stays open upon logout. What do you guys think?
Pull …

[LED-175] Fix Modal Issue #217

---

src/main/java/ledger/io/input/AbstractQFXConverter.java
src/main/java/ledger/io/input/AmericanExpressSavingsQFXConverter.java
src/main/java/ledger/io/input/FifthThirdBankQFXConverter.java
src/main/java/ledger/io/input/FirstDataCorpCSVConverter.java
src/main/java/ledger/io/input/USBankCSVConverter.java
src/main/java/ledger/io/input/USBankQFXConverter.java

The following three converters were updated to include check numbers:
- First Data Corp CSV
- US Bank CSV
- US Bank QFX
The following converters were not updated because we do not have appropriate sample files containing check numbers:
- American Express Savings QFX
- Chase Bank CSV
- Fifth Third Bank QFX
- PayPal CSV

[LED-163] Updated applicale converters to read in check numbers

---

src/main/java/ledger/user_interface/ui_controllers/component/tablecolumn/event_handler/AmountEventHandler.java
src/main/java/ledger/user_interface/ui_controllers/component/tablecolumn/event_handler/TypeEventHandler.java
src/main/java/ledger/user_interface/ui_controllers/window/TransactionPopupController.java

When entering transactions via the Add Transaction model or editing transaction in the table view, transactions of the Account Credit/Misc Credit types are restricted to non-negative amounts, and all other transaction types are restricted to non-positive amounts.
When editing transactions in the table view, if the user tries to switch a transaction's type to Account Credit/Misc Credit and the transaction has a negative amount, a confirmation dialogue will appear and ask the user if it's okay to flip the amount's sign to positive. If the user confirms, the edit goes through. If not, nothing happens. Vice versa for switching off of Account Credit/Misc Credit for transactions with positive amounts.

[LED-180] Implemented stricter debit/credit input sanitization

---

src/main/java/ledger/user_interface/ui_controllers/window/LoginPageController.java

This PR addresses to things
1. The Login screen will no longer suggest files that don't exist
2. The first time user popup only occurs if any preference data does not exist.

Last used Db file is no longer suggested if it doesnt exist, First time use update

---

src/main/java/ledger/user_interface/ui_controllers/window/IgnoredExpressionPopupController.java
src/main/java/ledger/user_interface/ui_controllers/window/ImportTransactionsPopupController.java
src/main/java/ledger/user_interface/ui_controllers/window/MainPageController.java
src/main/resources/fxml_files/IgnoredTransactionPopup.fxml
src/main/resources/fxml_files/ImportTransactionsPopup.fxml
src/main/resources/fxml_files/MainPage.fxml

Also renamed the window / button. 
On main page it is called `Ignored Transactions` and its title is `Automatic Ignored Transactions`
I could not get the title to fit on the button without making it two rows so just cut off the automatic part from the button.
#254 Should be merged first as this is a branch of that.

Moved the Ignored Transaction Button to Main page

---

src/main/java/ledger/user_interface/ui_controllers/window/ImportTransactionsPopupController.java

Selecting a file type will modify the file chooser's extension filters appropriately. I left in an All Files filter, but made the more specific one the default.
I discovered a couple TODOs in` ImportTransactionsPopController.java`. Made an issue for them since they seem to have fallen off our radar

[LED-120] Added auto detection of file types during import

---

src/main/java/ledger/user_interface/ui_controllers/component/tablecolumn/event_handler/AmountEventHandler.java
src/main/java/ledger/user_interface/ui_controllers/component/tablecolumn/event_handler/TypeEventHandler.java
src/main/java/ledger/user_interface/ui_controllers/window/RecurringTransactionController.java
src/main/java/ledger/user_interface/ui_controllers/window/TransactionPopupController.java

I changed the Add Transaction modal to allow transactions of Check and Cash types to have any dollar amount, both negative and positive. I also modified the logic in the Type and Amount column event handlers to behave this way as well. I believe I covered all cases, but please test this!

Fix allow all amounts for check and cash transactions
