Ledger-Software/Ledger

.travis.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties
src/main/java/ledger/Startup.java
src/main/java/ledger/database/IDatabase.java
src/main/java/ledger/database/enity/IEntity.java
src/main/java/ledger/database/enity/Setting.java
src/main/java/ledger/database/enity/Stat.java
src/main/java/ledger/database/enity/Transaction.java
src/main/java/ledger/database/manager/IManager.java
src/main/java/ledger/database/manager/ITimeSeries.java
src/main/java/ledger/database/manager/SettingManager.java
src/main/java/ledger/database/manager/StatManager.java
src/main/java/ledger/database/manager/TransactionManager.java
src/main/java/ledger/io/events/IIOEventGenerator.java
src/main/java/ledger/io/events/IStatusObserver.java
src/main/java/ledger/io/events/status/IOStatus.java
src/main/java/ledger/io/events/status/IOStatusResult.java
src/main/java/ledger/io/events/status/TransactionStatus.java
src/main/java/ledger/io/input/IInAdapter.java
src/main/java/ledger/io/output/IOutAdapter.java
src/test/java/ledger/ExampleTest.java
src/test/java/ledger/SQLiteTest.java
src/test/java/ledger/StartupTest.java
src/test/resources/README.md

- Setup basic class structure and documented
- Setup SQLite and tested

[LED-33] Setup of project architecture

---

src/main/java/ledger/database/enity/Account.java
src/main/java/ledger/database/enity/AccountBalance.java
src/main/java/ledger/database/enity/Note.java
src/main/java/ledger/database/enity/Payee.java
src/main/java/ledger/database/enity/Tag.java
src/main/java/ledger/database/enity/Transaction.java
src/main/java/ledger/database/enity/Type.java

Created object classes and documented them

LED39 Create and Document POJOs

---

src/main/java/ledger/database/IDatabase.java
src/main/java/ledger/database/enity/Account.java
src/main/java/ledger/database/enity/AccountBalance.java
src/main/java/ledger/database/enity/Note.java
src/main/java/ledger/database/enity/Payee.java
src/main/java/ledger/database/enity/Tag.java
src/main/java/ledger/database/enity/Transaction.java
src/main/java/ledger/database/enity/Type.java
src/main/java/ledger/database/storage/SQLiteDatabase.java
src/main/java/ledger/database/storage/SQLiteTableConstants.java
src/main/java/ledger/io/events/IIOEventGenerator.java
src/main/java/ledger/io/events/IStatusObserver.java
src/main/java/ledger/io/events/status/TransactionStatus.java
src/test/java/ledger/ExampleTest.java
src/test/java/ledger/SQLiteTest.java
src/test/java/ledger/database/storage/SQLiteDatabaseTest.java

Work from tonight. LED-44 is still in progress.

[LED-44] Removing Close Statements and Formating Project

---

src/main/java/ledger/user_interface/fxml_files/mainPage.fxml

Had to fix a few things before anyone else can take this and branch off it.

Fixed a few semantic things and gave a few elements the correct ids

---

src/main/java/ledger/database/enity/Account.java
src/main/java/ledger/database/enity/Type.java
src/main/java/ledger/io/input/DetectionResult.java
src/main/java/ledger/io/input/DuplicateDetector.java
src/test/java/ledger/io/input/DuplicateDetectorTest.java

We detect duplicates in between the converting and importing stages. It will be the controller's job to manage this. 
We detect duplicates by:
1. Pulling existing transactions from the database
2. Sorting these transactions
3. For each imported transaction, binary search for an equivalent
4. Sort items to import into lists based on whether or not an equivalent transaction was found in the DB

[LED-57] Duplicate Detection

---

src/main/java/ledger/database/storage/ISQLiteDatabaseAccount.java
src/main/java/ledger/database/storage/ISQLiteDatabaseNote.java
src/main/java/ledger/database/storage/ISQLiteDatabasePayee.java
src/main/java/ledger/database/storage/ISQLiteDatabaseTag.java
src/main/java/ledger/database/storage/ISQLiteDatabaseTransaction.java
src/main/java/ledger/database/storage/ISQLiteDatabaseType.java
src/test/java/ledger/database/storage/SQLiteDatabaseTest.java

- Removed all occurrences of "SELECT *", replaced with specific column names
- Added implementation to write back IDs to java objects for Payee, Account, etc. in insertTransaction and editTransaction
- Added implementation to insert notes when inserting transactions
- Refactored insertTransaction and editTransaction to lookup objects by ID when possible

[LED-63] Refactored SQLiteDatabase files

---

src/main/java/ledger/io/input/QfxConverter.java

Reduced the complexity of the convert method. Did this by extracting some methods to clarify the flow. Also added javadocs

Extracted methods and added javadoc

---

src/main/java/ledger/user_interface/ui_controllers/MainPageController.java
src/main/resources/fxml_files/mainPage.fxml

cleaned up so Tayler can use the list view better

cleaned up main page list view

---

src/main/java/ledger/user_interface/ui_controllers/AccountPopupController.java
src/main/java/ledger/user_interface/ui_controllers/ErrorPopupController.java
src/main/java/ledger/user_interface/ui_controllers/ExpenditureChartsController.java
src/main/java/ledger/user_interface/ui_controllers/IUIController.java
src/main/java/ledger/user_interface/ui_controllers/ImportTransactionsPopupController.java
src/main/java/ledger/user_interface/ui_controllers/LoginPageController.java
src/main/java/ledger/user_interface/ui_controllers/MainPageController.java
src/main/java/ledger/user_interface/ui_controllers/Startup.java
src/main/java/ledger/user_interface/ui_controllers/TransactionPopupController.java
src/main/resources/fxml_files/ErrorPopup.fxml
src/main/resources/fxml_files/ImportTransactionsPopup.fxml

Created a modal that will show the user any errors that occur during use.  Converted all system.out statements within the UI Controllers to use the modal,  and did some refactoring to get rid of a lot of duplicated code.

[LED-68] Helpful error message popups

---

src/main/java/ledger/user_interface/ui_controllers/AccountPopupController.java
src/main/java/ledger/user_interface/ui_controllers/GenericPopupController.java
src/main/java/ledger/user_interface/ui_controllers/IUIController.java
src/main/resources/fxml_files/GenericPopup.fxml

Modifed existing error popup to become a generic popup we can use for loading screens AND helpful error messages

[LED-72] Create Universal Popup for Loading Screens and Error Messages

---

src/main/java/ledger/controller/DbController.java
src/main/java/ledger/controller/ImportController.java
src/main/java/ledger/database/entity/Account.java
src/main/java/ledger/io/importer/Importer.java
src/main/java/ledger/user_interface/ui_controllers/AccountDropdown.java
src/main/java/ledger/user_interface/ui_controllers/ConverterDropdown.java
src/main/java/ledger/user_interface/ui_controllers/FileSelectorButton.java
src/main/java/ledger/user_interface/ui_controllers/ImportTransactionsPopupController.java
src/main/resources/fxml_files/ImportTransactionsPopup.fxml
src/test/java/ledger/io/importer/ImporterTest.java

Basic functionality is there but need to go through and do CSS again.
Notable changes:
* Each dropdown is it's own class (Account/Converter).
* FileSelectorButton used instead of having that code in multiple places.
Made a few changes to DbController so that it handles Nulls correctly.

LED-71 Transaction Import

---

src/main/java/ledger/user_interface/ui_controllers/MainPageController.java
src/main/java/ledger/user_interface/ui_models/TransactionModel.java
src/main/resources/fxml_files/MainPage.fxml
src/main/resources/fxml_files/mainPage.fxml

Finished wiring up table view. Still a lot to talk about. See open issues regarding this feature.
For now, we can display, edit, and delete transactions via the table view on the main UI page. Transactions can be added via the pop up dialogue.

[LED-69] Implement transaction table view on Main Page UI

---

src/main/resources/fxml_files/MainPage.fxml

removed unused name label and moved logout button

[LED-81] Remove Unused Labels

---

src/main/java/ledger/controller/DbController.java
src/main/java/ledger/database/storage/SQL/H2/H2Database.java
src/main/java/ledger/user_interface/ui_controllers/CreateDatabaseController.java
src/main/java/ledger/user_interface/ui_controllers/LoginPageController.java
src/main/java/ledger/user_interface/ui_controllers/Startup.java
src/main/resources/fxml_files/CreateDatabasePage.fxml
src/main/resources/fxml_files/LoginPage.fxml

Changed the application to open an encrypted H2 database instead of SQLite. Also added an additional button to allow the user to more elegantly create a db file. As we discussed with Sriram, im currently putting db files in the user directory.
Pull this down and test it! There are certainly improvements that can be made and the javafx controller stuff is surely not best practice.

enable database encryption

---

build.gradle
src/main/java/ledger/controller/DbController.java

* Fixes Gradle build file
* Register for normal updates on bulk import

LED-83 Update after bulk import

---

src/main/java/ledger/io/input/ChaseConverter.java

Made it so the payee field is not empty

Fixing the Payee field on ChaseConverter

---

src/main/java/ledger/user_interface/ui_controllers/TransactionPopupController.java

The transaction model in the popup didn't match our Transaction objects or DB structure

Quick fix for issue 55. 

---

build.gradle
src/main/java/ledger/user_interface/ui_controllers/CreateDatabaseController.java
src/main/java/ledger/user_interface/ui_controllers/LoginPageController.java
src/main/resources/fxml_files/CreateDatabasePage.fxml

Modified the CreateDatabasePage to allow the user to finish creation there instead of sending them back to the LoginPage. Uses the file name and password they enter to create a new DB file. Included a check to make sure the passwords are identicle. Then sends them directly to the MainPage.

[LED-76] Modified new file page. Now allows for creation all in the new window

---

src/main/java/ledger/user_interface/ui_controllers/AccountPopupController.java
src/main/java/ledger/user_interface/ui_controllers/CreateDatabaseController.java
src/main/java/ledger/user_interface/ui_controllers/LoginPageController.java
src/main/java/ledger/user_interface/ui_controllers/TransactionPopupController.java
src/main/java/ledger/user_interface/ui_controllers/TransactionTableView.java
src/main/java/ledger/user_interface/utils/InputSanitization.java

Created a new class, InputSanitizer.java, and extracted our existing work into it. Currently checks strings for non-empty and not null, but this is extracted so that its easily changable. Uses a regex to check amount entries. Decided not to touch dates since the best seems to be just trying it and catching exceptions anyway. We're also planning on replacing that field with a date picker, which would make that work redundant.
Double check the amount sanitization! I butchered some regex and it may or may not be broken.

[LED-79] Input sanitization

---

src/main/java/ledger/io/input/QfxConverter.java
src/main/java/ledger/io/input/TypeConversion.java
src/main/java/ledger/user_interface/ui_controllers/TransactionPopupController.java

Changed types as we discussed in standup on monday. Added a more complete list to the converter. The add transaction dropdown populates from this list. The add transaction controller now also uses the converter we made. The QfxImporter now inserts unknown types. 
Addresses issue#50

modified behavior of types

---

src/main/java/ledger/controller/DbController.java
src/main/java/ledger/user_interface/ui_controllers/AccountDropdown.java
src/main/java/ledger/user_interface/ui_controllers/CreateDatabaseController.java
src/main/java/ledger/user_interface/ui_controllers/LoginPageController.java
src/main/java/ledger/user_interface/ui_controllers/TransactionPopupController.java
src/main/resources/fxml_files/AddAccountPopup.fxml
src/main/resources/fxml_files/AddTransactionPopup.fxml
src/main/resources/fxml_files/MainPage.fxml

* Fix tab order on AddAccount
* Made Pending on Add Transaction more clear

LED-80 Adding several User Experience Improvements

---

src/main/java/ledger/user_interface/ui_controllers/TransactionTableView.java
src/main/java/ledger/user_interface/ui_models/TransactionModel.java
src/main/java/ledger/user_interface/utils/PayeeStringConverter.java
src/main/java/ledger/user_interface/utils/PendingStringConverter.java
src/main/java/ledger/user_interface/utils/TypeStringConverter.java

Implemented combobox table cells for Payee, Type, and Pending columns

F transaction table view dropdowns

---

src/main/java/ledger/io/input/TypeConversion.java
src/main/java/ledger/user_interface/ui_controllers/TransactionPopupController.java
src/main/java/ledger/user_interface/utils/TypeStringConverter.java
src/main/resources/fxml_files/AddTransactionPopup.fxml

I didn't use the TypeConverter because if the user wants to select an existing type we need to use the current DB entry. Those are stored in the existingTypes field so I draw from that.

Fixed the Transactiopn bug

---

src/main/java/ledger/controller/DbController.java
src/main/java/ledger/controller/ImportController.java
src/main/java/ledger/database/entity/Transaction.java
src/main/java/ledger/database/storage/table/TransactionTable.java
src/main/java/ledger/io/input/DuplicateDetector.java
src/main/java/ledger/user_interface/ui_controllers/AccountDropdown.java
src/main/java/ledger/user_interface/ui_controllers/AccountPopupController.java
src/main/java/ledger/user_interface/ui_controllers/DuplicateTransactionPopup.java
src/main/java/ledger/user_interface/ui_controllers/ImportTransactionsPopupController.java
src/main/java/ledger/user_interface/ui_controllers/TransactionPopupController.java
src/main/java/ledger/user_interface/ui_controllers/TransactionTableView.java
src/main/java/ledger/user_interface/utils/PayeeStringConverter.java
src/main/resources/fxml_files/DuplicateTransactionPopup.fxml
src/main/resources/fxml_files/GenericPopup.fxml
src/main/resources/fxml_files/ImportTransactionsPopup.fxml

Adds a popup to the end of bulk import that handles all the duplicates found in the system.
Does not deal with errored transactions.
Also changed:
* DbController methods had a no longer needed throws statement.
* Fixed Datastorage of dates.

LED-84 Bulk Import Duplicate Notifications

---

src/main/java/ledger/controller/DbController.java
src/main/java/ledger/controller/ImportController.java
src/main/java/ledger/controller/register/TaskWithArgsReturn.java
src/main/java/ledger/database/entity/Transaction.java
src/main/java/ledger/database/storage/SQL/ISQLDatabaseTransaction.java
src/main/java/ledger/io/input/DuplicateDetector.java
src/main/java/ledger/user_interface/ui_controllers/AccountDropdown.java
src/main/java/ledger/user_interface/ui_controllers/AccountPopupController.java
src/main/java/ledger/user_interface/ui_controllers/ConverterDropdown.java
src/main/java/ledger/user_interface/ui_controllers/CreateDatabaseController.java
src/main/java/ledger/user_interface/ui_controllers/DuplicateTransactionPopup.java
src/main/java/ledger/user_interface/ui_controllers/IUIController.java
src/main/java/ledger/user_interface/ui_controllers/ImportTransactionsPopupController.java
src/main/java/ledger/user_interface/ui_controllers/LoginPageController.java
src/main/java/ledger/user_interface/ui_controllers/MainPageController.java
src/main/java/ledger/user_interface/ui_controllers/TransactionTableView.java
src/main/java/ledger/user_interface/ui_models/TransactionModel.java
src/main/java/ledger/user_interface/utils/PayeeStringConverter.java
src/main/java/ledger/user_interface/utils/PendingStringConverter.java
src/main/resources/fxml_files/ChoiceBox.fxml

Move where database calls are hit in controller loading.
Ran full code format.

Fix scene builder load exceptions

---

src/main/resources/fxml_files/AddTransactionPopup.fxml

Addressing issue#51. Just reordered fxml elements

Fixed tab ordering in add account window

---

src/main/java/ledger/user_interface/ui_controllers/AccountPopupController.java
src/main/java/ledger/user_interface/ui_controllers/TransactionPopupController.java
src/main/java/ledger/user_interface/utils/InputSanitization.java

This is adding some input sanitization and also some error boxes on add transaction

[LED-98] Transaction Errors 

---

src/main/java/ledger/controller/DbController.java
src/main/java/ledger/database/IDatabase.java
src/main/java/ledger/database/storage/SQL/ISQLDatabaseTransaction.java
src/main/java/ledger/user_interface/ui_controllers/AccountDropdown.java
src/main/java/ledger/user_interface/ui_controllers/FilteringAccountDropdown.java
src/main/java/ledger/user_interface/ui_controllers/MainPageController.java
src/main/java/ledger/user_interface/ui_controllers/TransactionTableView.java
src/main/resources/fxml_files/MainPage.fxml

You can now use the account dropdown to filter the transactions. Added a dummy account to allow the user to view all transactions if they want. Added a new db function and controller call for this.

[LED-94] Filtering displayed transactions by the selected account

---

src/main/java/ledger/user_interface/ui_controllers/Startup.java
src/main/resources/fxml_files/MainPage.fxml
src/main/resources/fxml_files/TransactionTableView.fxml

This was done in preparation of adding a search box.
Main Page is now much cleaner and resizes in a decent manner. 
There is also now a min size for the window.

Refactor of Main Page

---

src/main/resources/fxml_files/ImportTransactionsPopup.fxml

Added the labels per Sean's request

[LED-101] added import descriptors

---

src/main/resources/fxml_files/CreateDatabasePage.fxml

[LED-99] Added default filename to the create db window

---

src/main/java/ledger/user_interface/ui_controllers/FilteringAccountDropdown.java

Instead of having that blank box

Auto select AllAccounts on page initialize

---

src/main/java/ledger/user_interface/ui_controllers/IUIController.java
src/main/java/ledger/user_interface/ui_controllers/ImportTransactionsPopupController.java
src/main/java/ledger/user_interface/ui_controllers/LoginPageController.java
src/main/java/ledger/user_interface/ui_controllers/MainPageController.java
src/main/java/ledger/user_interface/ui_controllers/Startup.java
src/main/resources/fxml_files/LoginPage.fxml

Made it so that none of the windows are resizable. Now our UI won't do weird things.

[LED-106] made all windows unresizable

---

src/main/java/ledger/controller/DbController.java
src/main/java/ledger/user_interface/ui_controllers/MainPageController.java
src/main/java/ledger/user_interface/ui_controllers/PasswordPromptController.java
src/main/resources/fxml_files/MainPage.fxml
src/main/resources/fxml_files/PasswordPrompt.fxml

Turned out to be a little more complicated than we though. Modified the DB controller to store a reference to the storage location. I had to shutdown the db before copying the file (darn file locks). After the copy I prompt the user for the password again and reconnect them to the db

[LED-100] Added Exporting of data

---

src/main/java/ledger/user_interface/ui_controllers/MainPageController.java
src/main/java/ledger/user_interface/ui_controllers/TransactionTableView.java
src/main/resources/fxml_files/MainPage.fxml

CJ & I implemented the UI and backend for searching the transaction table. The text input is used to search the amount, payee, and category columns.
The filter will be updated when the user hits "Enter" while in the text box or clicks the "Search" button. The filter will be cleared when the user clicks the "Clear" button (same effect as hitting "Enter" w/ a black text field).
Pull it down and test it, please! Let me know any feedback, thanks!

Implemented transaction fuzzy search, fixed minor UI bugs.

---

src/main/java/ledger/user_interface/ui_controllers/CreateDatabaseController.java
src/main/resources/fxml_files/CreateDatabasePage.fxml

Using File Chooser now. It will ask if you want to replace the file. One you hit Ok it will Delete the old file if it exists

[LED-108] Duplicate File in new DB selector.

---

src/main/java/ledger/database/entity/Payee.java
src/main/java/ledger/database/storage/SQL/ISQLDatabaseTag.java
src/main/java/ledger/user_interface/ui_controllers/CreateDatabaseController.java
src/main/java/ledger/user_interface/ui_controllers/FilteringAccountDropdown.java
src/main/java/ledger/user_interface/ui_controllers/LoginPageController.java
src/main/java/ledger/user_interface/ui_controllers/MainPageController.java
src/main/java/ledger/user_interface/ui_controllers/PasswordPromptController.java
src/main/java/ledger/user_interface/ui_controllers/Startup.java
src/main/java/ledger/user_interface/ui_controllers/UserTransactionInput.java
src/main/java/ledger/user_interface/ui_models/TransactionModel.java
src/main/java/ledger/user_interface/utils/InputSanitization.java
src/main/java/ledger/user_interface/utils/LocalDateTableCell.java
src/main/java/ledger/user_interface/utils/PayeeStringConverter.java
src/main/resources/fxml_files/AddAccountPopup.fxml
src/main/resources/fxml_files/AddTransactionPopup.fxml
src/main/resources/fxml_files/ChoiceBox.fxml
src/main/resources/fxml_files/CreateDatabasePage.fxml
src/main/resources/fxml_files/DuplicateTransactionPopup.fxml
src/main/resources/fxml_files/ExpenditureCharts.fxml
src/main/resources/fxml_files/GenericPopup.fxml
src/main/resources/fxml_files/ImportTransactionsPopup.fxml
src/main/resources/fxml_files/LoginPage.fxml
src/main/resources/fxml_files/MainPage.fxml
src/main/resources/fxml_files/PasswordPrompt.fxml
src/main/resources/fxml_files/SetPassword.fxml
src/main/resources/fxml_files/TransactionTableView.fxml
src/main/resources/fxml_files/UserTransactionInput.fxml

Some code cleanup to fix some logic.
* Login Page is Resize-able
* Main Page is Resize-able 
Also did a full code format.

General Fixes / Cleanup from this week's merges.

---

src/main/resources/css/colorStyle.css
src/main/resources/fxml_files/LoginPage.fxml

Now we have a bearable blue color palette. I also messed with the height of the login page because it was driving me crazy.

Updated UI Colors

---

src/main/java/ledger/user_interface/ui_controllers/AccountPopupController.java

Just parsing as a double then convert to int internally.

Fixing the add account bug that sean encoutered

---

.travis.yml
src/main/java/ledger/database/storage/table/NoteTable.java
src/main/java/ledger/database/storage/table/TagToTransTable.java
src/main/java/ledger/database/storage/table/TransactionTable.java
src/main/java/ledger/user_interface/ui_controllers/FilteringAccountDropdown.java
src/main/java/ledger/user_interface/ui_controllers/MainPageController.java
src/main/resources/fxml_files/MainPage.fxml

Added a button to delete the selected account. The delete cascades to all transactions associated with the account. After the delete, the transaction table will display "All Accounts"
I also discovered a much easier and cleaner way to display dialogs. We should talk about this and look into converting the way we do it. It'd be supes easy

[LED-117] Account Deletion

---

build.gradle
src/main/java/ledger/updater/GitHubChecker.java
src/main/java/ledger/user_interface/ui_controllers/Startup.java
src/main/java/ledger/user_interface/ui_controllers/UpdateConfirmation.java
src/main/resources/fxml_files/UpdateConfirmation.fxml

Only runs when program is running inside a jar.

[LED-102] Auto update

---

src/main/java/ledger/user_interface/ui_controllers/IUIController.java
src/main/java/ledger/user_interface/ui_controllers/MainPageController.java

Rewrote our setupErrorPopup to use JavaFX alerts. Errors with exceptions have a dropdown menu where you can view the stack trace.
Stubbed out changing the icon in the corner of the box if we ever get one.

[LED-133] Refactored dialog boxes

---

.travis.yml
build.gradle

[LED-132] Working on Deploying on Tags

---

src/main/java/ledger/updater/GitHubChecker.java
src/main/java/ledger/updater/OldVersionFinder.java
src/main/java/ledger/user_interface/ui_controllers/OldVersionArchiver.java
src/main/java/ledger/user_interface/ui_controllers/Startup.java
src/main/java/ledger/user_interface/utils/VersionComparer.java
src/main/resources/fxml_files/DeleteArchivePrompt.fxml

Version checking is done by JAR name. Could move it to manifest but by doing it by name it helps with compatibility and is more robust in general.
Test by putting several jars in the same directory with the version being determined by the name (Ledger-x.x.x.jar)

[LED-131] Archive or Delete old versions on start

---

src/main/java/ledger/user_interface/ui_controllers/ExpenditureChartsController.java
src/main/java/ledger/user_interface/ui_controllers/IUIController.java
src/main/java/ledger/user_interface/ui_controllers/LoginPageController.java
src/main/java/ledger/user_interface/ui_controllers/MainPageController.java

Sean's description on JIRA said that a highlighted or different-colored 'Add Account' button on the main page would be sufficient to show a first time user how to get started. I didn't think that would be super intuitive, so upon a first time logging in, I set an alert that tells them how to set up a DB, and then once they get to the main page, another alert pops up and tells them that the first thing they need to do is create an account. Check it out and let me know what you think. For the first popup to show, you can't have any databases already existing in the home directory.

LED-134 Logic for first time users

---

src/main/java/ledger/user_interface/ui_controllers/CreateDatabaseController.java
src/main/java/ledger/user_interface/ui_controllers/LoginPageController.java

Our current code saves files as LedgerDb.mv.db.mv.db on Macs. This should fix that.

Fix for wonky file extensions

---

src/main/java/ledger/controller/DbController.java
src/main/java/ledger/database/IDatabase.java
src/main/java/ledger/database/entity/Payee.java
src/main/java/ledger/database/storage/SQL/ISQLDatabasePayee.java
src/main/java/ledger/database/storage/SQL/ISQLDatabaseTag.java
src/test/java/ledger/database/storage/H2DatabaseTest.java
src/test/java/ledger/database/storage/SQLiteDatabaseTest.java

Added database functions to delete all transactions for a payee.
Wired up controller to delete all tags for payee, insert and remove tags, get all tags for payee, and update existing payee
Existing payee entity had to modified to store a list of its tags.

[LED-23/24/25] Backend for tagging

---

src/main/java/ledger/user_interface/ui_controllers/TransactionTableView.java
src/main/java/ledger/user_interface/utils/AmountComparator.java
src/main/java/ledger/user_interface/utils/PayeeComparator.java
src/main/java/ledger/user_interface/utils/TypeComparator.java

I believe this will fix all the table sorting issues, go ahead and test it out though. I haven't implemented a comparator for tags, and I'm not sure how we'd like to sort those. Something to discuss at the next meeting*.

[LED-145] Implemented comparators for Amount, Payee, and Type

---

src/main/java/ledger/controller/DbController.java
src/main/java/ledger/controller/ImportController.java
src/main/java/ledger/io/importer/Importer.java
src/main/java/ledger/io/input/AbstractCSVConverter.java
src/main/java/ledger/user_interface/ui_controllers/IUIController.java
src/main/java/ledger/user_interface/ui_controllers/Startup.java
src/main/java/ledger/user_interface/utils/LocalDateTableCell.java
src/main/java/ledger/user_interface/utils/VersionComparer.java

We've got a shitton of invalid JavaDocs. Went ahead and fixed about 30 of them. Not sure how to fix the remaining errors, they're mostly in CJs github checker and CSV parser

Java doc fixes

---

src/main/java/ledger/controller/DbController.java
src/main/java/ledger/database/IDatabase.java
src/main/java/ledger/database/entity/AccountBalance.java
src/main/java/ledger/database/storage/SQL/H2/H2Database.java
src/main/java/ledger/database/storage/SQL/ISQLDatabaseAccountBalance.java
src/main/java/ledger/database/storage/SQL/SQLite/SQLiteDatabase.java
src/main/java/ledger/database/storage/table/AccountBalanceTable.java
src/main/java/ledger/user_interface/ui_controllers/component/AccountBalanceLabel.java
src/main/java/ledger/user_interface/ui_controllers/window/AccountPopupController.java
src/main/java/ledger/user_interface/ui_controllers/window/MainPageController.java
src/main/resources/fxml_files/Label.fxml
src/main/resources/fxml_files/MainPage.fxml
src/test/java/ledger/database/storage/H2DatabaseTest.java

So I added a label above the account dropdown box to display the current account's balance. If the All Accounts aggregation is selected, you'll get a net balance for all accounts. There is no support for checkpointing yet (since we have no implementaiton for it anyway), but it'll be easy to add later.
- The Label works as a custom UI element. Its a label with its own fancy-schmancy controller. 
- Added database code to support Account Balances. 
- Added account balances in the db. 
- Added tests for said db code. 
- Wired up controller to db. 
- Wired up UI to controller. 
- Changed account insertion to create an initial account balance.

[LED-142] Account Balances Display

---

src/main/resources/fxml_files/LoginPage.fxml

Should fix any issues with #119 
Need someone with a mac to check this ( @taylerhow ).

Should fix Issue#119

---

src/main/java/ledger/user_interface/ui_controllers/component/UserTransactionInput.java
src/main/java/ledger/user_interface/utils/InputSanitization.java
src/main/resources/fxml_files/UserTransactionInput.fxml

Added Support for checks on adding a transaction.
If the users selects checks from the dropdown the check fields show up.
The check must be an integer number and must not be null
When the user saves the transaction it is added on to the end of the note.

[LED-121] Support for checks

---

src/main/java/ledger/user_interface/ui_controllers/component/TransactionTableView.java
src/main/java/ledger/user_interface/ui_controllers/component/tablecolumn/AAmountColumn.java
src/main/java/ledger/user_interface/ui_controllers/component/tablecolumn/AmountCreditColumn.java
src/main/java/ledger/user_interface/ui_controllers/component/tablecolumn/AmountDebitColumn.java
src/main/java/ledger/user_interface/utils/AAmountStringConverter.java
src/main/java/ledger/user_interface/utils/AmountCreditStringConverter.java
src/main/java/ledger/user_interface/utils/AmountDebitStringConverter.java
src/main/java/ledger/user_interface/utils/AmountStringConverter.java
src/main/resources/fxml_files/TransactionTableView.fxml

NOTE: I'm aware that there are horizontal sizing issues with displaying the additional columns, but I'll have to sort those out after I stitch together all the different table view changes.
For now, please test the logical functionality of these features (make the app larger to accomodate):
- Toggling Debit/Credit view
- Editing amount in both standard and Debit/Credit view
- Sorting by amount in both standard and Debit/Credit view

[LED-144] Implemented Debit/Credit columns. Still some minor UI issues

---

src/main/java/ledger/database/entity/Transaction.java
src/main/java/ledger/database/storage/SQL/ISQLDatabaseTransaction.java
src/main/java/ledger/database/storage/table/TransactionTable.java
src/main/java/ledger/user_interface/ui_controllers/component/TransactionTableView.java
src/main/java/ledger/user_interface/ui_controllers/component/UserTransactionInput.java
src/main/java/ledger/user_interface/ui_controllers/component/tablecolumn/CheckNumberColumn.java
src/main/java/ledger/user_interface/utils/CheckNumberStringConverter.java
src/main/resources/fxml_files/TransactionTableView.fxml

We're merging into f_tableViewChanges so we can consolidate all the merge conflicts for the table view into one branch.
Added Check number funcitonality. Instead of appending check numbers to the end of the notes, we now have a new column to display them in. The column can be shown/hidden in the right click menu. We assume the standard four digit check numbers.

Optional Check Numbers Column

---

src/main/java/ledger/controller/DbController.java
src/main/java/ledger/user_interface/ui_controllers/component/TransactionTableView.java
src/main/java/ledger/user_interface/ui_controllers/component/UserTransactionInput.java
src/main/java/ledger/user_interface/ui_controllers/component/tablecolumn/AccountColumn.java
src/main/java/ledger/user_interface/ui_controllers/component/tablecolumn/PayeeColumn.java
src/main/java/ledger/user_interface/utils/AmountStringConverter.java

Added the ability to add transactions from the right click context menu. During standup, we need to talk about making the account column editable. 
The original goal was to add a bottom row in which you could input data, but that doesn't seem to be possible.

insert from right click context menu

---

src/main/java/ledger/controller/DbController.java
src/main/java/ledger/user_interface/ui_controllers/component/AccountBalanceLabel.java
src/main/java/ledger/user_interface/ui_controllers/component/PayeeTableView.java
src/main/java/ledger/user_interface/ui_controllers/component/TransactionTableView.java
src/main/java/ledger/user_interface/ui_controllers/component/tablecolumn/PayeeColumn.java

The payee dropdowns in the table broke. This should fix it

Somebody borked a merge

---

src/main/java/ledger/user_interface/ui_controllers/Startup.java
src/main/java/ledger/user_interface/ui_controllers/component/LogoutButton.java

Here's a PR that's basically less than a line of code. Hurrah.

[LED-161] made login window unresizeable and fixed CJs 'Leger' typo

---

src/main/java/ledger/user_interface/ui_controllers/component/ExportButton.java

Fixed infinite loop in export bug

---

src/main/resources/fxml_files/PasswordPrompt.fxml

there was a wrong id in the fxml

Fix PasswordPrompt coloring

---

src/main/resources/fxml_files/MainPage.fxml
src/main/resources/fxml_files/TransactionTableView.fxml

This should fix the transaction scrolling issue.

Transaction Scroll fix

---

src/main/resources/fxml_files/MainPage.fxml

Originally was thinking about doing this as tabs, but the accordion style seemed to flow better as it allows the user to have more then one group open.
Also do we want to be able to minimize the left hand side. If so does that include the Account filter or how do we want to handle that.

[LED-160] Left hand User Controls (Grouping)

---

src/main/java/ledger/user_interface/ui_controllers/component/NoteEditInputController.java
src/main/java/ledger/user_interface/ui_controllers/component/tablecolumn/NoteColumn.java
src/main/resources/fxml_files/NoteEditInput.fxml
src/main/resources/fxml_files/TransactionTableView.fxml

This pr fixes the Notes Column UI.
There is only one text area now and it responds to changes in focus
The notes column also now sizes correctly when it is focused and also when somthing else changes the row size.

[LED-159] F notes ui fixes

---

src/main/resources/fxml_files/ExpenditureCharts.fxml

Expenditure Title Fix

---

src/main/resources/fxml_files/PayeeTableWindow.fxml

Payee editor header fix

---

src/main/java/ledger/controller/DbController.java
src/main/java/ledger/controller/register/TaskWithArgs.java
src/main/java/ledger/controller/register/TaskWithArgsReturn.java
src/main/java/ledger/controller/register/TaskWithReturn.java
src/main/java/ledger/database/storage/SQL/ISQLDatabaseTransaction.java

This should fix the bug with editing the transaction table and not seeing updates.

Fixes Get Transaction By Id and adds some better error logging

---

src/main/java/ledger/user_interface/ui_controllers/window/LoginPageController.java

Tell user to select file / put in password on login screen if they try to login without propper input

Login Screen: User Directions

---

src/main/java/ledger/user_interface/ui_controllers/window/CreateDatabaseController.java

When creating a new DB file after you choose the location the first password field will be auto focused.

Auto Select Password field after selecting file

---

src/main/resources/fxml_files/MainPage.fxml

All tabs on left side should now be closed when the app is opened.
(Smallest PR?)

Change Miscellaneous Tab to being default to closed

---

src/main/java/ledger/controller/DbController.java

Payee dropdown didnt populate after import. It does now

Payee dropdown fix

---

src/main/java/ledger/user_interface/ui_controllers/component/tablecolumn/PayeeColumn.java

Quick fix so that we update UI stuff on the right thread

Fixing payee dropdown...again

---

src/main/java/ledger/user_interface/ui_controllers/window/AccountPopupController.java

Added an on enter key event to the text boxes in the Add Account window. Also reworded some of the error messages to be more accurate

Add onEnter to account window. Reword some of our errors

---

.gitignore

Updated gitignore to include /out directory that is created when IntelliJ builds the project

Updated gitignore (and taking a title shot for smallest PR)

---

src/main/java/ledger/user_interface/ui_controllers/window/CreateDatabaseController.java

Changed the function call to open main window in center of screen, consistent with regular login. Addresses issue #201

Fixed main window centering bug (issue #201)

---

src/main/java/ledger/user_interface/ui_controllers/window/IgnoredExpressionPopupController.java

Fix JavaDoc Error

---

src/main/java/ledger/user_interface/ui_controllers/Startup.java

Fixed Startup to disable resizing the login window

---

src/main/java/ledger/user_interface/utils/VersionComparer.java
src/test/java/ledger/user_interface/utils/VersionComparerTest.java

Version Tests and Bug Fix

---

src/main/resources/fxml_files/UpdateConfirmation.fxml

Fixes Update Whitespace

---

src/main/java/ledger/user_interface/ui_controllers/component/AccountBalanceLabel.java
src/main/java/ledger/user_interface/ui_controllers/component/AccountInfo.java
src/main/java/ledger/user_interface/ui_controllers/component/TransactionTableView.java
src/main/java/ledger/user_interface/ui_controllers/window/ImportTransactionsPopupController.java
src/main/java/ledger/user_interface/ui_controllers/window/MainPageController.java
src/main/java/ledger/user_interface/ui_controllers/window/TransactionPopupController.java
src/main/resources/fxml_files/AccountInfoItem.fxml
src/main/resources/fxml_files/MainPage.fxml

Got rid of the account dropdown and account balance label. Replaced them with a collapsible menu bar like the other stuff. Let me know what you think!

[LED-143] Change Account Filter UI

---

src/main/java/ledger/database/entity/Account.java
src/main/java/ledger/database/entity/Transaction.java
src/main/java/ledger/user_interface/ui_controllers/component/TransactionTableView.java
src/main/java/ledger/user_interface/ui_controllers/component/tablecolumn/AAmountColumn.java
src/main/java/ledger/user_interface/ui_controllers/component/tablecolumn/RunningBalanceColumn.java
src/main/java/ledger/user_interface/utils/TransactionRunningAccountBalanceCalculator.java
src/main/resources/fxml_files/TransactionTableView.fxml

Running balances are calculated immediately after transactions are retrieved from DB.
Test this please! Thanks.

Implemented running account balance column

---

README.md

Here's my first draft at the code pipeline documentation. Please read through it a couple times and feel free to suggest sentence structure changes, etc. as I feel it may be a little wordy. Also make sure I didn't miss anything. I was unsure what to say about the lock on master, since it currently only technically has to have one approved peer review before it thinks it's good to go. Hopefully what I put there was good enough.

[LED-166] code pipeline documentation

---

src/main/resources/fxml_files/MainPage.fxml

Account Label ListView Fix

---

src/test/java/ledger/user_interface/UiIntegrationTestsRunner.java

Looks like the issue that caused this to be needed is fixed already so just removing dead code.

[LED-171] Fix double test run

---

src/test/java/ledger/user_interface/AccountIntegrationTests.java
src/test/java/ledger/user_interface/LoginIntegrationTests.java
src/test/java/ledger/user_interface/MiscellaneousIntegrationTests.java
src/test/java/ledger/user_interface/TransactionIntegrationTests.java
src/test/java/ledger/user_interface/UiIntegrationTestsRunner.java

**Work In Progress**
The work for LED-174 (travis fix) will also go into this branch before it can merge. I just wanted to open it so that you guys can check out the extra integration tests on time.
The rerun fix has been merged in. We should no longer need to retry a test because of an undeleted default DB.
We now test
- Login
- Logout
- Adding an account through the AddAccount window
- Deleting an account via the Delete Account button
- Inserting a transaction through the Add Transaction window
- Inserting a transaction through the window with invalid input
- Inserting a transaction through the TableView's right click menu
- Editing a transaction through the TableView
- Deleting a transaction through the TableView
- Data export
- First time use dialogs

Integration Tests

---

src/main/java/ledger/user_interface/ui_controllers/window/CreateDatabaseController.java
src/main/java/ledger/user_interface/ui_controllers/window/LoginPageController.java
src/main/java/ledger/user_interface/utils/PreferenceHandler.java

This uses java preferences to load the previously used db file. 
This needs tested on a Mac.

[LED-116] Last DB file Load

---

src/main/java/ledger/user_interface/ui_controllers/component/UserTransactionInput.java
src/main/java/ledger/user_interface/ui_controllers/component/charts/ExpenditurePieChart.java
src/main/resources/fxml_files/UserTransactionInput.fxml
src/test/java/ledger/user_interface/LoginIntegrationTests.java

Pretty simple, just renamed some stuff. Take a look through the app, see if i missed anything.
Also fixed one of our UI tests that we broke with the Account Balance fix. Oops

[LED-182] Renamed all instances of Category to Tag

---

src/main/java/ledger/user_interface/ui_controllers/component/TransactionTableView.java

Filtering now account for hidden columns, and the table view will update whenever a change is made to the list of displayed columns. Currently, the Date & Cleared columns are the only columns that are not filtered on.

[LED-178] Updated filtering mechanics to account for hidden columns

---

src/main/java/ledger/user_interface/ui_controllers/component/AccountInfo.java
src/main/java/ledger/user_interface/ui_controllers/window/MainPageController.java
src/main/resources/fxml_files/AccountInfoItem.fxml

Addresses issue #245 
Also right aligns the balance in the UI

Fix account balance and update UI

---

src/main/java/ledger/database/entity/Note.java
src/main/java/ledger/database/entity/Tag.java
src/main/java/ledger/user_interface/ui_controllers/IUIController.java
src/main/java/ledger/user_interface/ui_controllers/component/charts/DateAxis.java
src/main/java/ledger/user_interface/ui_controllers/component/charts/ExpenditureLineChart.java
src/main/java/ledger/user_interface/ui_controllers/component/charts/ExpenditurePayeePieChart.java
src/main/java/ledger/user_interface/ui_controllers/component/charts/ExpenditureTagPieChart.java
src/main/java/ledger/user_interface/ui_controllers/component/charts/IncomeBarChart.java
src/main/java/ledger/user_interface/ui_controllers/component/charts/NetBalanceLineChart.java
src/main/java/ledger/user_interface/ui_controllers/window/ExpenditureChartsController.java
src/main/resources/fxml_files/ExpenditureCharts.fxml

Changed up charts with a time axis to have greater detail.
Also can someone else run the UI tests. They seem to be failing on my computer.
This also contains the fix for the account balance and chart discrepancies, LED-182

[LED-176] More Stat Charts

---

src/main/java/ledger/user_interface/ui_controllers/component/ExportButton.java
src/main/resources/fxml_files/PasswordPrompt.fxml

Users can now choose a file to export to instead of a directory. We auto fill the suggested name and filter to *.mv.db

[LED-196] Change data export to allow user to choose file name

---

src/main/java/ledger/user_interface/ui_controllers/window/FinanceAnalysisController.java
src/main/java/ledger/user_interface/ui_controllers/window/MainPageController.java
src/main/resources/fxml_files/FinanceAnalysisPage.fxml
src/main/resources/fxml_files/MainPage.fxml

Renamed the button on the main page and also the expenditure charts window to say "finance analysis" etc. Also renamed the controller class and fxml file to match.

[LED-188] Rename Track Spending

---

src/main/java/ledger/user_interface/ui_controllers/window/MainPageController.java
src/main/resources/fxml_files/MainPage.fxml

The search filter is now updated any time the text in the filter's text box is changed. I've also removed the 'Search' button, since it's no longer necessary.

Implemented table view filter update on change

---

src/main/java/ledger/user_interface/ui_controllers/window/IgnoredExpressionPopupController.java
src/main/resources/fxml_files/IgnoredTransactionPopup.fxml

Adds a done button that closes the popup window to the Ignore Editor page.

[LED-197] Add done button to Ignore Editor

---

.travis.yml
build.gradle
src/main/java/ledger/user_interface/ui_controllers/component/FileSelectorButton.java
src/main/java/ledger/user_interface/ui_controllers/window/CreateDatabaseController.java
src/test/java/ledger/user_interface/AccountIntegrationTests.java
src/test/java/ledger/user_interface/LoginIntegrationTests.java
src/test/java/ledger/user_interface/MiscellaneousIntegrationTests.java
src/test/java/ledger/user_interface/TransactionIntegrationTests.java
src/test/java/ledger/user_interface/UiIntegrationTestsRunner.java

Fixes the UI Tests on Linux and makes them a bit more reliable overall for all OS. This was originally for fixing Travis but have not found out exactly what is causing it to break but I am much closer.
Test this on:

Fix UI Tests on Linux

---

src/main/java/ledger/user_interface/ui_controllers/component/FileSelectorButton.java

Fixed NPE in fileSelectorButton

---

src/test/java/ledger/user_interface/MiscellaneousIntegrationTests.java

Somehow we got the wrong filename in our regex

Fix for broken export integreation test

---

src/main/java/ledger/user_interface/ui_controllers/window/CreateDatabaseController.java
src/main/java/ledger/user_interface/ui_controllers/window/LoginPageController.java

Changes the file-chooser to use the last used directory.

[LED-193] Load last Directory

---

src/main/java/ledger/user_interface/ui_controllers/IUIController.java
src/main/java/ledger/user_interface/ui_controllers/window/FinanceAnalysisController.java
src/main/java/ledger/user_interface/ui_controllers/window/MainPageController.java
src/main/java/ledger/user_interface/utils/PreferenceHandler.java

This adds in an introduction to the Statistics page.
Also this includes a modal update that makes the default modality Window_Modal and sets the parent so when children are open you cant change the parent window.

[LED-189] Financial Analysis Help

---

src/main/java/ledger/controller/DbController.java
src/main/java/ledger/user_interface/ui_controllers/component/TagBuilderControl.java
src/main/java/ledger/user_interface/ui_controllers/component/UserTransactionInput.java

Used on both the Transaction page and on the Payee Editor (Automatic Tags)

[LED-184] Auto Complete Tags

---

src/main/java/ledger/user_interface/ui_controllers/component/TransactionTableView.java
src/main/java/ledger/user_interface/ui_controllers/window/MainPageController.java

Also added informative dialogue if there is nothing to undo.
To clarify, according to @cjm721, we don't have a Redo feature implemented.

[LED-202] Added undo to right click menu

---

src/main/java/ledger/user_interface/ui_controllers/window/AccountPopupController.java

Now we can't make accounts with the same name. I made it case insensitive, so for example we can't have account a and account A. That registers as the same account. If we don't wanna do that, let me know and I'll change it.

[LED-204] Disallow Duplicate Account Names

---

src/main/java/ledger/controller/DbController.java
src/main/java/ledger/database/IDatabase.java
src/main/java/ledger/database/storage/SQL/ISQLDatabaseTag.java
src/main/java/ledger/user_interface/ui_controllers/component/TagEditorTableView.java
src/main/java/ledger/user_interface/ui_controllers/window/MainPageController.java
src/main/java/ledger/user_interface/ui_controllers/window/TagEditorTableWindow.java
src/main/resources/fxml_files/MainPage.fxml
src/main/resources/fxml_files/TagEditorTableView.fxml
src/main/resources/fxml_files/TagEditorTableWindow.fxml

Ready to be reviewed now!
I've added UI for the Tag Editor. It's accessible through the Edit Tags button on the Main Page. There's currently support for editing, deleting, and merging tags. I don't plan on adding functionality to create new tags via the tag editor, since tags are automatically created when written to a transaction for the first time.
Some things to consider when testing:
- Proper tables are updated after a Tag operation is executed
- Delete, edit, and merge operations propagate to other tables (auto-tagging, transactions) properly
- Logical flow merging tags is intuitive for the user

[LED-185] Tag editor (Ready for review)

---

src/main/java/ledger/user_interface/ui_controllers/component/tablecolumn/event_handler/TagEventHandler.java

This deals with the following:
#287 
#285
#283
#281

Fixes tagging

---

src/main/java/ledger/database/entity/RecurringTransaction.java

I saw Jesse write the code for this before, somehow got blown away in merge or something.
#279 
#280

Fixes Recurring Editor State

---

src/main/java/ledger/user_interface/ui_controllers/component/UserTransactionInput.java

You should now be able to add all types of Transactions from the popup window.
#276

Fixes Add Transactions

---

src/main/java/ledger/user_interface/ui_controllers/component/UserTransactionInput.java

Fixed bug where changing Type dropdown selection would clear Account dropdown selection
Named my branch the wrong thing. Sorry :(

Fixed bug in Add Transaction modal

---

src/main/java/ledger/database/entity/RecurringTransaction.java
src/main/java/ledger/user_interface/ui_controllers/window/MainPageController.java

Addressing Issue #293 
So if three days have passed since you logged on, a recurring transaction the triggers daily will now add three transactions

Implemented backfill of recurring transactions

---

src/main/java/ledger/user_interface/ui_controllers/component/tablecolumn/event_handler/CalendarEventHandler.java
src/main/java/ledger/user_interface/utils/CalendarTableCell.java

Addressing Issue #278. The dates in the Editor Window table cells should now be accurate.

fix editor window calendar columns
